### ISSUE TITLE
Unable to sign up for beta waitlist

### ISSUE THREAD

**Issue by TechPro424** [upscayl/upscayl.github.io#8]
When I fill in details and sign up for waitlist on website, I get a pop up error saying `Please fill in all the fields correctly.` even though I have filled in the fields
![image](https://github.com/upscayl/upscayl.github.io/assets/86620085/1ce894cb-1186-45b3-8c17-13ea0cf34f61)

**Comment by NayamAmarshe** [comment]
Oh, I'm not sure why that's happening. I'll push a fix. Thank you so much for letting me know!

**Comment by NayamAmarshe** [comment]
It should start working again :)

**Comment by TechPro424** [comment]
same issue

**Comment by NayamAmarshe** [comment]
> same issue

Really? I tried myself and it seems to be working: 
<img width="677" alt="image" src="https://github.com/upscayl/upscayl.github.io/assets/25067102/8a757315-b847-4358-acc8-290a0f6273b9">

**Comment by NayamAmarshe** [comment]
It must be the cache.

Press Ctrl/Cmd + Shift + R and it should fix the issue :)

**Comment by TechPro424** [comment]
tried it, still same issue :(

**Comment by NayamAmarshe** [comment]
> tried it, still same issue :(

Could you please email me? nayam.emikx@aleeas.com

I'll add you to the waitlist manually. Sorry for the trouble 🙏🏻

**Comment by TechPro424** [comment]
emailed 
(and don't apologize, this stuff happens :) )

**Comment by NayamAmarshe** [comment]
> emailed (and don't apologize, this stuff happens :) )

Thank you! I've addded you to the list :D

The error was appearing because of the name. The name field doesn't allow numbers, that's why it's throwing errors 😅

**Comment by TechPro424** [comment]
No problem :)
(Also, some feedback: make the error messages clearer next time)
